GET http://localhost:5176/games

### This is use as a seperater to have mulitple request in the same file.
GET http://localhost:5176/games/2


### create a game
POST http://localhost:5176/create
Content-Type: application/json

{
    "name": "Minecraf",
    "genre": "",
    "price":"19.99",
    "releaseDate":"2011-11-18"
}

### update a game from the game list
PUT http://localhost:5176/games/update/1
Content-Type: application/json

{
    "name": "COD (Call of Duty)",
    "genre": "Combat",
    "price": 199.99,
    "releaseDate": "1990-05-19"
}